import { Link } from "react-router-dom";
import "./Home.css";

const work = [["/images/home-living.jpg", "A calm, modern living room", "Warm minimalism"], ["/images/home-bedroom.jpg", "A softly layered bedroom", "Soft sanctuary"], ["/images/home-dining.jpg", "A considered dining space", "Naturally refined"]];
const services = [["01", "Interior painting", "Spaces that feel considered, from a single room to your whole home."], ["02", "Exterior painting", "Long-lasting protection and a welcoming first impression."], ["03", "Textures & effects", "Tactile detail and custom finishes that make walls a feature."]];

export default function Home() {
  return <main>
    <section className="home-hero"><div className="hero-paint paint-one"></div><div className="hero-paint paint-two"></div><div className="container hero-layout"><div className="hero-copy"><p className="eyebrow">Your walls, beautifully considered</p><h1>Make room for a <em>fresh</em> point of view.</h1><p className="hero-text">Premium painting and texture work for homes that deserve a finish as personal as the people inside them.</p><div className="hero-actions"><Link to="/contact" className="btn btn-primary">Start your colour story <b>→</b></Link><a href="https://wa.me/919356535803" target="_blank" rel="noreferrer" className="text-link">Chat on WhatsApp <span>↗</span></a></div><div className="hero-trust"><div className="avatars"><i></i><i></i><i></i></div><span><strong>150+ happy homes</strong><br />painted with care</span></div></div><div className="hero-image"><img src="/images/home-hero.jpg" alt="Elegant freshly painted living room" /><div className="image-tag"><span>01</span><p>From wall prep to final brushstroke,<br /><b>we leave nothing to chance.</b></p></div></div></div></section>
    <section className="intro-section"><div className="container intro-grid"><p className="eyebrow">The Elite difference</p><div><h2 className="section-heading">Painting is more than colour on a wall.</h2><p className="section-copy">It is the light that meets you in the morning, the backdrop to the moments that matter, and a chance to make your space feel entirely new.</p></div><Link className="round-link" to="/about">Meet the team <span>→</span></Link></div></section>
    <section className="services-preview"><div className="container"><div className="section-top"><div><p className="eyebrow">What we do</p><h2 className="section-heading">Finish, elevated.</h2></div><Link className="text-link" to="/services">Explore all services <span>→</span></Link></div><div className="service-preview-grid">{services.map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p><Link to="/services">Discover <b>↗</b></Link></article>)}</div></div></section>
    <section className="work-section"><div className="container"><div className="section-top"><div><p className="eyebrow">Recent transformations</p><h2 className="section-heading">A little colour goes a long way.</h2></div><Link className="text-link" to="/gallery">View the gallery <span>→</span></Link></div><div className="home-work-grid">{work.map(([image, alt, title], index) => <figure key={image} className={`home-work-${index}`}><img src={image} alt={alt} /><figcaption>{title} <span>↗</span></figcaption></figure>)}</div></div></section>
    <section className="cta-section"><div className="container cta-card"><div><p className="eyebrow">Your next chapter starts here</p><h2>Ready to come home<br />to something <em>beautiful?</em></h2></div><Link to="/contact" className="btn btn-light">Get a free quote <b>→</b></Link></div></section>
  </main>;
}
